/* 
 * Simple Inventory API
 *
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Hello struct {

	Msg string `json:"msg"`

	Test string `json:"test,omitempty"`

	Int_ *int64 `json:"int,omitempty"`

	Bool_ *bool `json:"bool,omitempty"`
}
