/* 
 * Simple Inventory API
 *
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type InventoryItem struct {

	Id string `json:"id"`

	Name string `json:"name"`

	ReleaseDate string `json:"releaseDate"`

	Manufacturer Manufacturer `json:"manufacturer"`
}
